/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestUI.java
 *
 * Created on 2009-5-21, 9:27:21
 */

package net.dgie.xmltask;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;


/**
 *
 * @author admin
 */
public class Run extends javax.swing.JFrame {

    /** Creates new form TestUI */
    public Run() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@10.1.1.185:1521:TESTPU").createEntityManager();
        maintasklistQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Maintasklist m");
        maintasklistList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : maintasklistQuery.getResultList();
        autoTaskPanel = new javax.swing.JPanel();
        updateIntervalLabel = new javax.swing.JLabel();
        updateIntervalTextField = new javax.swing.JTextField();
        autoUpdateButton = new javax.swing.JButton();
        minuteLabel = new javax.swing.JLabel();
        systemExitButton = new javax.swing.JButton();
        manualTaskPanel = new javax.swing.JPanel();
        sectionManualUpdateButton = new javax.swing.JButton();
        totalManualUpdateButton = new javax.swing.JButton();
        taskScrollPane = new javax.swing.JScrollPane();
        taskTable = new javax.swing.JTable();
        messagePanel = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        autoTaskPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("网页自动抓取"));

        updateIntervalLabel.setText("更新时间间隔：");

        updateIntervalTextField.setText("10");
        updateIntervalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIntervalTextFieldActionPerformed(evt);
            }
        });

        autoUpdateButton.setText("启动");
        autoUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoUpdateButtonActionPerformed(evt);
            }
        });

        minuteLabel.setText("分钟");

        systemExitButton.setText("退出");
        systemExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout autoTaskPanelLayout = new javax.swing.GroupLayout(autoTaskPanel);
        autoTaskPanel.setLayout(autoTaskPanelLayout);
        autoTaskPanelLayout.setHorizontalGroup(
            autoTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoTaskPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(updateIntervalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateIntervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minuteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(autoUpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(systemExitButton))
        );
        autoTaskPanelLayout.setVerticalGroup(
            autoTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoTaskPanelLayout.createSequentialGroup()
                .addGroup(autoTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(autoTaskPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(autoTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateIntervalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoUpdateButton)
                            .addComponent(updateIntervalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minuteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(systemExitButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        manualTaskPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "eMail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        sectionManualUpdateButton.setText("部分执行");
        sectionManualUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionManualUpdateButtonActionPerformed(evt);
            }
        });

        totalManualUpdateButton.setText("全部执行");
        totalManualUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalManualUpdateButtonActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, maintasklistList, taskTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${taskid}"));
        columnBinding.setColumnName("任务ID");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${taskname}"));
        columnBinding.setColumnName("任务名称");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${remoteurl}"));
        columnBinding.setColumnName("远程URL");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        taskTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskTableMouseClicked(evt);
            }
        });
        taskScrollPane.setViewportView(taskTable);

        javax.swing.GroupLayout manualTaskPanelLayout = new javax.swing.GroupLayout(manualTaskPanel);
        manualTaskPanel.setLayout(manualTaskPanelLayout);
        manualTaskPanelLayout.setHorizontalGroup(
            manualTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manualTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(sectionManualUpdateButton)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manualTaskPanelLayout.createSequentialGroup()
                .addContainerGap(494, Short.MAX_VALUE)
                .addComponent(totalManualUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        manualTaskPanelLayout.setVerticalGroup(
            manualTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manualTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manualTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sectionManualUpdateButton)
                    .addComponent(taskScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(totalManualUpdateButton))
        );

        messageLabel.setText("程序准备就绪");

        javax.swing.GroupLayout messagePanelLayout = new javax.swing.GroupLayout(messagePanel);
        messagePanel.setLayout(messagePanelLayout);
        messagePanelLayout.setHorizontalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        messagePanelLayout.setVerticalGroup(
            messagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manualTaskPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoTaskPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(autoTaskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualTaskPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalManualUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalManualUpdateButtonActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_totalManualUpdateButtonActionPerformed

    private void systemExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemExitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_systemExitButtonActionPerformed

    Timer timer = null;
    private void autoUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoUpdateButtonActionPerformed
        if( autoUpdateButton.getText().equals( "启动" ) ) {
            timer = new Timer();
            PropertyReader pr = new PropertyReader();
            long period = Long.valueOf( updateIntervalTextField.getText() ) * 1000 * 60;
            timer.scheduleAtFixedRate( new MainTimerTask( updateIntervalTextField.getText() ), new Date(), period );
            autoUpdateButton.setText( "停止" );
            messageLabel.setText( "已启动" );
        }
        else {
            autoUpdateButton.setText( "启动" );
            timer.cancel();
            messageLabel.setText( "已停止" );
        }      
}//GEN-LAST:event_autoUpdateButtonActionPerformed

    private void updateIntervalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIntervalTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_updateIntervalTextFieldActionPerformed
    List<String>  taskIdList = new ArrayList();
    private void taskTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskTableMouseClicked
        taskIdList.clear();
        for(  Integer i: taskTable.getSelectedRows() ) {
            taskIdList.add( taskTable.getValueAt( i, 0 ) + "" );
        }
    }//GEN-LAST:event_taskTableMouseClicked

    private void sectionManualUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionManualUpdateButtonActionPerformed
       messageLabel.setText( "正在执行" );

       //关闭自动更新
       if( timer != null ) {
            autoUpdateButton.setText( "启动" );
            timer.cancel();
       }
       for( String id: taskIdList ) {
           System.out.print( id + " " );
       }
       System.out.println();
       messageLabel.setText( "部分执行完成执行" );
    }//GEN-LAST:event_sectionManualUpdateButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Run().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel autoTaskPanel;
    private javax.swing.JButton autoUpdateButton;
    private javax.persistence.EntityManager entityManager;
    private java.util.List<net.dgie.xmltask.Maintasklist> maintasklistList;
    private javax.persistence.Query maintasklistQuery;
    private javax.swing.JPanel manualTaskPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JLabel minuteLabel;
    private javax.swing.JButton sectionManualUpdateButton;
    private javax.swing.JButton systemExitButton;
    private javax.swing.JScrollPane taskScrollPane;
    private javax.swing.JTable taskTable;
    private javax.swing.JButton totalManualUpdateButton;
    private javax.swing.JLabel updateIntervalLabel;
    private javax.swing.JTextField updateIntervalTextField;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
